# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

branches:
  only:
  - master

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: LctvSwift.xcodeproj
xcode_scheme: LctvSwift Tests iOS

# cache: cocoapods
#podfile: Example/Podfile
#before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example

script:
- xcodebuild -list
- set -o pipefail && xcodebuild test -workspace LctvSwift.xcworkspace -scheme "LctvSwift Tests iOS" -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
