# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

branches:
  only:
  - master

osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
xcode_project: Example/LctvSwift.xcodeproj
xcode_scheme: LctvSwift-Example

# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/LctvSwift.xcworkspace -scheme LctvSwift-Example -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
